### ISSUE TITLE
Getting undefined is not a function error when adding plugins

### ISSUE THREAD

**Issue by Mulletfingers999** [voxel/voxel-plugins#3]
Hello all,
When I try calling plugins.add, I get the following error:
`Uncaught TypeError: undefined is not a function `
Here is my code:
```javascript
var createPlugins = require('voxel-plugins');
var plugins = createPlugins(game, {require:require});

//Load Plugins
plugins.add('voxel-health', {maxHealth: 20});
plugins.add('voxel-health-bar', {});
plugins.loadAll();
```
The error occurs where I attempt to add the voxel-health and the voxel-health-bar plugins.

Thank you all in advanced

**Comment by deathcap** [comment]
When using the `require:require` option, plugins have to be `require()`'d in the calling module before using `plugins.add()`, something like this:

```javascript
require('voxel-health');
require('voxel-health-bar');
var createPlugins = require('voxel-plugins');
var plugins = createPlugins(game, {require:require});

//Load Plugins
plugins.add('voxel-health', {maxHealth: 20});
plugins.add('voxel-health-bar', {});
plugins.loadAll();
```

if you still see this when adding the require()s, could you include the full stacktrace for the "Uncaught TypeError: undefined is not a function" error.

In voxel-plugins 0.5.0+, added a new 'loaders' option which makes the dependencies clearer:

```javascript
var createPlugins = require('voxel-plugins');
var plugins = createPlugins(game, {loaders:
  'voxel-health': require('voxel-health'),
  'voxel-health-bar': require('voxel-health-bar')
});

//Load Plugins
plugins.add('voxel-health', {maxHealth: 20});
plugins.add('voxel-health-bar', {});
plugins.loadAll();
```
