### ISSUE TITLE
Question regarding README

### ISSUE THREAD

**Issue by z3t0** [voxel/voxel-plugins#5]
```
examine the optional pluginInfo for dependency ordering, build up the loading graph, and save the
```
Could you please explain what you mean by 'build up the loading graph'? Thanks

**Comment by alanszlosek** [comment]
Each plugin can optionally specify `pluginInfo`, which can include loading order. If you look at the `voxel-inventory-creative` plugin, it specifies two other plugins that it must be loaded after. See here, lines 8 and 9: https://github.com/voxel/voxel-inventory-creative/blob/master/inventory-creative.coffee

**Comment by z3t0** [comment]
oh thanks!
