### ISSUE TITLE
Explain please

### ISSUE THREAD

**Issue by z3t0** [voxel/voxel-plugins#6]
Hi could you please explain how this line works, I am still quite new to some things in javascript.

https://github.com/deathcap/voxel-plugins/blob/master/plugins.js#L196

**Comment by deathcap** [comment]
return !!(plugin && plugin.pluginEnabled);

!! coerces to boolean, so this returns true if the plugin exists (not a "falsey" value) and is enabled, otherwise false

**Comment by z3t0** [comment]
thanks!
